title: Anil Sigdel
logo: /assets/img/logo2.jpg
description: Postdoc in Animal Genomics
theme: jekyll-theme-minimal
# can also do "remote_theme: THEME-NAME, replacing THEME-NAME with the name of the theme as shown in the README of the theme's repository."
